# Generated by Django 4.1 on 2022-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=122)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
